/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JuegoGrafico;

import JuegoCodigo.Code;
import JuegoCodigo.PanelTablero;
import javax.swing.JPanel;

/**
 *
 * @author manue
 */
public class Juego extends javax.swing.JPanel {

    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
        
        initComponents();

        // Cargar imágenes y llenar el tablero
        Code code = new Code();
        code.cargarImagenes();
        code.llenarVector();

        // Crear panel del tablero con las 24 imágenes
        PanelTablero tablero = new PanelTablero(Code.imagenestablero);

        // Establecer el layout principal del JFrame
        this.setLayout(new java.awt.BorderLayout());

        // Crear un panel auxiliar para alinear el tablero a la izquierda
        JPanel surIzquierda = new JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));
        surIzquierda.add(tablero);

        // Agregar el panel auxiliar al SUR del BorderLayout
        this.add(surIzquierda, java.awt.BorderLayout.SOUTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 773, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
