/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JuegoGrafico;

import JuegoCodigo.Code;
import JuegoCodigo.Musica;
import JuegoCodigo.PanelTablero;
import java.awt.BorderLayout;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author manue
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private JPanel panelCentral;
    public static Musica musica=new Musica();
    int cont;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);//para que se abra en pantalla completa

        musica.reproducir("/Sonido/RatDance.wav");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SalirBoton = new javax.swing.JButton();
        CreditosBoton = new javax.swing.JButton();
        InstruccionesBoton = new javax.swing.JButton();
        JugarBoton = new javax.swing.JButton();
        ControlMusicaBoton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adivina quien!");
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        SalirBoton.setText("Salir");
        SalirBoton.setPreferredSize(new java.awt.Dimension(200, 100));
        SalirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBotonActionPerformed(evt);
            }
        });

        CreditosBoton.setText("Creditos");
        CreditosBoton.setPreferredSize(new java.awt.Dimension(200, 100));
        CreditosBoton.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        CreditosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditosBotonActionPerformed(evt);
            }
        });

        InstruccionesBoton.setText("Instrucciones");
        InstruccionesBoton.setPreferredSize(new java.awt.Dimension(200, 100));
        InstruccionesBoton.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        InstruccionesBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstruccionesBotonActionPerformed(evt);
            }
        });

        JugarBoton.setText("Jugar");
        JugarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugarBotonActionPerformed(evt);
            }
        });

        ControlMusicaBoton.setText("⏸");
        ControlMusicaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ControlMusicaBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(CreditosBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(InstruccionesBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(SalirBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JugarBoton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ControlMusicaBoton)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(JugarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InstruccionesBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SalirBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CreditosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(ControlMusicaBoton)
                .addGap(23, 23, 23))
        );

        SalirBoton.getAccessibleContext().setAccessibleName("SalirBoton");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //BOTON DE SALIR
    private void SalirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBotonActionPerformed
        musica.pausar();
        dispose();//Se cierra solo ese Jframe
    }//GEN-LAST:event_SalirBotonActionPerformed
    //BOTON DE CREDITOS
    private void CreditosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditosBotonActionPerformed
        Creditos creditos= new Creditos();//creamos un obejot para enseñar el panel de creditos
        this.getContentPane().removeAll();                       // Limpia lo anterior
        this.getContentPane().setLayout(new BorderLayout());     // Usa BorderLayout
        this.getContentPane().add(new Creditos(), BorderLayout.CENTER); // Agrega el panel
        this.revalidate();                                       // Actualiza el layout
        this.repaint();                                          // Redibuja la ventana
    }//GEN-LAST:event_CreditosBotonActionPerformed
    //BOTON DE INSTRUCCIONES
    private void InstruccionesBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstruccionesBotonActionPerformed
        Instrucciones instrucciones= new Instrucciones();//creamos un obejot para enseñar el panel de Instrucciones
        this.getContentPane().removeAll();                       // Limpia lo anterior
        this.getContentPane().setLayout(new BorderLayout());     // Usa BorderLayout
        this.getContentPane().add(new Instrucciones(), BorderLayout.CENTER); // Agrega el panel
        this.revalidate();                                       // Actualiza el layout
        this.repaint();                                          // Redibuja la ventana
    }//GEN-LAST:event_InstruccionesBotonActionPerformed

    private void JugarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugarBotonActionPerformed
        Juego juego= new Juego();//creamos un obejot para enseñar el panel de juego
        this.getContentPane().removeAll();                       // Limpia lo anterior
        this.getContentPane().setLayout(new BorderLayout());     // Usa BorderLayout
        this.getContentPane().add(new Juego(), BorderLayout.CENTER); // Agrega el panel
        this.revalidate();                                       // Actualiza el layout
        this.repaint();
        
        //Se pone el boton aqui porque de otra manera se acciona dos veces ya que se manda a llamar Juego 
        Random rand=new Random();//para generar un numero random
        PanelTablero.aleatorio.addActionListener(e->{
            int numale=rand.nextInt(24);//genera un numero entre 0-23
            Juego.jugadorAle=Code.imagenestablero[numale];//le guardamos a la variable el nombre del jugador que toco
            Juego.jugadorAle=Juego.jugadorAle.replace("/JugadoresProyecto/", "").replace(".png", "");//se le quita lo que no es el nombre del jugador
            Juego.MJ.mostrarJugador("Tu jugador es: ");
            //System.out.println(Juego.jugadorAle);
        });//Boton para seleccionar un jugador en aleatorio
        
        //Boton que hace que avances para ya jugar
        PanelTablero.avanzar.addActionListener(e->{
            JuegoPrincipal JP=new JuegoPrincipal();
            this.getContentPane().removeAll();                       // Limpia lo anterior
            this.getContentPane().setLayout(new BorderLayout());     // Usa BorderLayout
            this.getContentPane().add(new Juego(), BorderLayout.CENTER); // Agrega el panel
            this.revalidate();                                       // Actualiza el layout
            this.repaint();
        });//Boton para avanzar
    }//GEN-LAST:event_JugarBotonActionPerformed

    private void ControlMusicaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ControlMusicaBotonActionPerformed
        if (ControlMusicaBoton.isSelected()) {
            musica.pausar();
            ControlMusicaBoton.setText("▶");
        } else {
            musica.continuar();
            ControlMusicaBoton.setText("⏸");
    }
    }//GEN-LAST:event_ControlMusicaBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ControlMusicaBoton;
    private javax.swing.JButton CreditosBoton;
    private javax.swing.JButton InstruccionesBoton;
    private javax.swing.JButton JugarBoton;
    private javax.swing.JButton SalirBoton;
    // End of variables declaration//GEN-END:variables
}
